name: ESLint

on:
  pull_request:
    paths-ignore:
      - '**/node_modules/**'
      - 'package.json'
      - 'yarn.lock'
      - '**.md'
    branches:
      - master

jobs:
  run_eslint:
    name: MessageQuote eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install
      - name: eslint
        run: yarn run lint
