name: Prettier

on:
  pull_request:
    paths-ignore:
      - '**/node_modules/**'
      - 'package.json'
      - 'yarn.lock'
      - '**.md'
    branches:
      - master

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: yarn install
      - name: Prettier#check
        run: yarn run check
